### ISSUE TITLE
Change XPI /sign/hash to return asn1 digestinfo

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#126]
Per irc:

:catlee

> is it doing any asn1 encoding?
> the mar file needs something like https://github.com/catlee/build-mar/blob/split_sigs/src/mardor/signing.py#L201 at some point

:g-k

> margo might do that here: https://github.com/mozilla-services/margo/blob/master/sign.go#L142-L147
> I assume /sign/file does that at some point, so we can update /sign/hash

cc @catlee @jvehent whether ^ is correct

**Comment by jvehent** [comment]
I dug into that rabbit hole for a bit, and I don't think MAR files currently use ASN1 encoded signatures. From what I can extract from existing MAR files, they just contain the bigint of the hash encrypted with the private key. A straight up 512 bytes bigint.

https://play.golang.org/p/x83zUi1vgtR

Sooo maybe wontfix? Catlee and I will continue digging for a little longer until we reach a warm spot.

**Comment by jvehent** [comment]
For future ref, we found out that Go does encode input hashes into asn.1 DigestInfo prior to signing them with rsa PKCS1 v1.5. That happens here: 

https://github.com/golang/go/blob/master/src/crypto/rsa/pkcs1v15.go#L210 -> https://github.com/golang/go/blob/master/src/crypto/rsa/pkcs1v15.go#L313 -> https://github.com/golang/go/blob/master/src/crypto/rsa/pkcs1v15.go#L233

Because this happens under the hood of the rsa Sign() function, the logic currently in place remains correct. The caller, in this case Signing Script, only need to send a raw, unencoded, hash and will get back a raw RSA signature to be inserted in a MAR file.
