### ISSUE TITLE
Autograph should never recompress files in APKs

### ISSUE THREAD

**Issue by snorp** [mozilla-services/autograph#164]
The decision on whether a file is DEFLATE or STORE within an APK is often explicitly made by the application. The option to do this was added in ab0180072f5ae341722081e77894029caf738d8d, but it should be the default behavior. It is very unexpected for a signing tool to mutate the input beyond what is required to apply the signature.

**Comment by jvehent** [comment]
Could you point to a specific example of file being changed from DEFLATE to STORE (or vice versa) when being signed? It would help us pinpoint the actual problem.

> It is very unexpected for a signing tool to mutate the input beyond what is required to apply the signature.

This is mostly due to zipalign, which android requires, and which we originally implemented in the APK signer of autograph to avoid requiring sdk tools on the caller's side, but we're moving away from that decision.

**Comment by cpeterso** [comment]
@Johanlorenzo Is this Autograph bug fixed now that mozilla-releng/signingscript#88 has been merged?

**Comment by JohanLorenzo** [comment]
Yeah, I think we can consider this bug fixed thanks to:
* https://github.com/mozilla-services/autograph/pull/153 for projects using autograph-edge (like Firefox VR)
* https://github.com/mozilla-releng/signingscript/pull/88 for Fennec and Firefox Focus.

Please let me know if another project has the same kind of problems.

**Comment by g-k** [comment]
>  it should be the default behavior

Completely agree. I was hesitant to potentially break other APKs at the time and require clients to run `zipalign` after signing, but `passthrough` should be the default and only option.

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1506598 to track this.
