### ISSUE TITLE
run monitor from multiple routes / network perspectives

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#168]
For envs with internal and external routes to autograph test both (e.g. have routes for different network segments and have the monitor use an IP from each segment).

cc @milescrabill for feedback / feasibilty

**Comment by milescrabill** [comment]
This is feasible. I've set up the groundwork for the monitor to be able to use the external NLB in addition to the internal ELB (whitelisting outbound NAT gateway IPs).

Right now, the endpoint that the monitor hits is configured in the monitor's config file. It would be nice if we could configure the endpoint as an environment variable so that we can more easily vary the endpoint that the monitor hits (internal vs. external).

**Comment by g-k** [comment]
With #272 this is configured by the `AUTOGRAPH_URL` env var (ending *with* a trailng slash)
