### ISSUE TITLE
The signature array

### ISSUE THREAD

**Issue by ncloudioj** [mozilla-services/autograph#17]
Hey @jvehent ,

Having a quick question about the return value. The signature is currently of the JSON array type, for example,
```JSON
"signatures": [
      {
        "encoding": "b64url",
        "signature": "PWUsOnvlhZV0I4k4hwGFMc3LQcUlS-l1UwD0cNevPv3ux7T9moHX_JZHc75cmnyo-hUkW6s-c6AaNr_dyxg2528OLY53voIqwTsiYll1iPElS9TV0xOo3awuwnYcctOp",
        "hashalgorithm": "sha256"
      }
    ] 
```
So is there any special reason for that? To me this is a bit unnecessary if autograph only attaches one signature to each piece of content.

**Comment by jvehent** [comment]
The idea is to return multiple signatures if needed. We could, for example, return a sha256 and a sha384 signature, or a b64url and regular b64. Since the position of the response must match the position of the request, we can't just add more responses without breaking the mapping, so having a signature array seemed more flexible.

Do you think this is a bad pattern?

**Comment by ncloudioj** [comment]
Ah, I see. Make sense.

Currently, Splice only grabs the first one, and discards all the rest, as it only attaches one signature to the content then upload to S3. We might need to consider multiple encoding signatures if necessary.

Thanks for clarifying it.

**Comment by jvehent** [comment]
See #24
