### ISSUE TITLE
Support 'browser_specific_settings' in add-ons manifest

### ISSUE THREAD

**Issue by wagnerand** [mozilla-services/autograph#174]
Firefox supports '[browser_specific_settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings)' as a synonym for applications, however,  autograph does not know about this, which leads to signing the file using the wrong add-on ID.

More info in https://github.com/mozilla/addons-server/issues/9989

**Comment by g-k** [comment]
As far as I can tell autograph's XPI /sign/file endpoint always takes the ID as a request param and doesn't try to pull it out of the XPI manifest: https://github.com/mozilla-services/autograph/blob/d33b9c90e377b962a70c5a6dc5fef0b7135ce643/signer/xpi/xpi.go#L292-L293

We might need to change the EE cert we generate though since we use the signer CN and fall back to the   request ID:

https://github.com/mozilla-services/autograph/blob/d33b9c90e377b962a70c5a6dc5fef0b7135ce643/signer/xpi/xpi.go#L302-L311

then hash the CN to include in the cert DNSNames:

https://github.com/mozilla-services/autograph/blob/master/signer/xpi/x509.go#L52-L62

**Comment by g-k** [comment]
Maybe autograph should return a 400 error if the request ID doesn't match the ID from the manifest.json.

**Comment by g-k** [comment]
Per :aswan on slack: 

> If they're both present, the browser favors browser_specific_settings and warns that "applications" is ignored

**Comment by EnTeQuAk** [comment]
I'm starting to work on https://github.com/mozilla/addons-server/issues/9308 and I'm wondering if this is a blocker for this work to go live eventually, especially since that synonym will probably become more and more used in the future.

**Comment by wagnerand** [comment]
As far as I understand, as long as AMO always provides the add-on ID in the request, we should be good.

**Comment by jvehent** [comment]
> Maybe autograph should return a 400 error if the request ID doesn't match the ID from the manifest.json.

I think AMO should do this. We should keep Autograph as focused on signing as possible.

> As far as I understand, as long as AMO always provides the add-on ID in the request, we should be good.

This is correct, the ID needs to be set in the request and Autograph will simply use that value.
https://github.com/mozilla-services/autograph/tree/master/signer/xpi#signature-request
No parsing of manifest happens during signing, beyond the generation of the signature files.

**Comment by wagnerand** [comment]
@jvehent Can I ask that we reconsider the decision of closing this issue?

autograph does parse the manifest in https://github.com/mozilla-services/autograph/blob/2bc1af88b684316e9dca7501f3f910c3b128329d/tools/sign-addon/sign.py#L73

That part parses `applications.gecko.id` which is incomplete. I believe we should completely that function (`get_guid`) and solely rely on the ID being part of the request or add `browser_specific_settings.gecko.id` to make autograph compliant to the specification.
