### ISSUE TITLE
Remove xpi ee backdating from armagaddon mitigation

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autograph#334]
During armagaddon, we added backdating of EE certs issued by the XPI signer: https://github.com/mozilla-services/autograph/blob/master/signer/xpi/x509.go#L112-L114

This mitigation should be removed.

ni: @mozkeeler @rhelmer Can we ship this now?

**Comment by mozkeeler** [comment]
Yes - if I recall correctly, we did this because one proposed solution was to verify add-on certificates at a particular time rather than "now", which meant the end-entities had to be valid at a time when the intermediate also was. That's not the solution we went with, and the currently-shipped code still uses "now" to verify certificates, so we should be able to remove this.

**Comment by jvehent** [comment]
Perfect! We'll remove it in a future release.
